/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sscc.views;

import sscc.views.images.ImageLoader;

/**
 *
 * @author valquirialbr
 */
public class FrmMenu extends javax.swing.JFrame {

    private FrmVoluntario frmVoluntario;
    private FrmValidacion frmValidacion;
    private FrmUpdVoluntario frmUpdVoluntario;
    private FrmAptitudes frmAptitudes;
    private FrmBSectores frmBSectores;
    private FrmDesactualizados frmDesactualizados;
    private FrmSector frmSector;
    private FrmUpdSector frmUpdSector;
    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();  
        setIconImage(ImageLoader.obtenerImagen("favicon.ico"));
        this.setLocationRelativeTo(null);
    }
    
    public void disposeFrames(){
        if(frmVoluntario != null && frmVoluntario.isVisible())
            frmVoluntario.dispose();
        if(frmUpdVoluntario != null && frmUpdVoluntario.isVisible())
            frmUpdVoluntario.dispose();
        if(frmValidacion != null && frmValidacion.isVisible())
            frmValidacion.dispose();
        if(frmAptitudes != null && frmAptitudes.isVisible())
            frmAptitudes.dispose();
        if(frmBSectores != null && frmBSectores.isVisible())
            frmBSectores.dispose();
        if(frmUpdSector != null && frmUpdSector.isVisible())
            frmUpdSector.dispose();
        if(frmSector != null && frmSector.isVisible())
            frmSector.dispose();
        if(frmDesactualizados != null && frmDesactualizados.isVisible())
            frmDesactualizados.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mbMenu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();
        mVoluntarios = new javax.swing.JMenu();
        miRegistroV = new javax.swing.JMenuItem();
        miValidacionV = new javax.swing.JMenuItem();
        miActualizacionV = new javax.swing.JMenuItem();
        mSectores = new javax.swing.JMenu();
        miRegistroS = new javax.swing.JMenuItem();
        miActualizaS = new javax.swing.JMenuItem();
        mConsultas = new javax.swing.JMenu();
        miCriterioAptitudes = new javax.swing.JMenuItem();
        miCriterioSectores = new javax.swing.JMenuItem();
        miDatosDesactualizados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Voluntarios");
        setBackground(new java.awt.Color(51, 51, 255));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sscc/views/images/background.png"))); // NOI18N

        mbMenu.setBackground(new java.awt.Color(153, 153, 153));
        mbMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mbMenu.setForeground(new java.awt.Color(255, 255, 255));
        mbMenu.setBorderPainted(false);
        mbMenu.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N

        mArchivo.setText("Archivo");

        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mArchivo.add(miSalir);

        mbMenu.add(mArchivo);

        mVoluntarios.setText("Voluntarios");

        miRegistroV.setText("Registro de Voluntarios");
        miRegistroV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistroVActionPerformed(evt);
            }
        });
        mVoluntarios.add(miRegistroV);

        miValidacionV.setText("Validación de datos");
        miValidacionV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miValidacionVActionPerformed(evt);
            }
        });
        mVoluntarios.add(miValidacionV);

        miActualizacionV.setText("Actualización de datos");
        miActualizacionV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualizacionVActionPerformed(evt);
            }
        });
        mVoluntarios.add(miActualizacionV);

        mbMenu.add(mVoluntarios);

        mSectores.setText("Sectores");

        miRegistroS.setText("Crear Sector");
        miRegistroS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistroSActionPerformed(evt);
            }
        });
        mSectores.add(miRegistroS);

        miActualizaS.setText("Actualizar Sector");
        miActualizaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualizaSActionPerformed(evt);
            }
        });
        mSectores.add(miActualizaS);

        mbMenu.add(mSectores);

        mConsultas.setText("Consultas");

        miCriterioAptitudes.setText("Criterio de Aptitudes");
        miCriterioAptitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriterioAptitudesActionPerformed(evt);
            }
        });
        mConsultas.add(miCriterioAptitudes);

        miCriterioSectores.setText("Criterio de Sectores");
        miCriterioSectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCriterioSectoresActionPerformed(evt);
            }
        });
        mConsultas.add(miCriterioSectores);

        miDatosDesactualizados.setText("Datos desactualizados");
        miDatosDesactualizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDatosDesactualizadosActionPerformed(evt);
            }
        });
        mConsultas.add(miDatosDesactualizados);

        mbMenu.add(mConsultas);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        disposeFrames();
        dispose();
    }//GEN-LAST:event_miSalirActionPerformed

    private void miValidacionVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miValidacionVActionPerformed
        disposeFrames();
        frmValidacion = new FrmValidacion();
        frmValidacion.setVisible(true);
    }//GEN-LAST:event_miValidacionVActionPerformed

    private void miActualizacionVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualizacionVActionPerformed
        disposeFrames();
        frmUpdVoluntario = new FrmUpdVoluntario();
        frmUpdVoluntario.setVisible(true);
    }//GEN-LAST:event_miActualizacionVActionPerformed

    private void miRegistroVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroVActionPerformed
        disposeFrames();
        frmVoluntario = new FrmVoluntario();
        frmVoluntario.setVisible(true);
    }//GEN-LAST:event_miRegistroVActionPerformed

    private void miRegistroSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroSActionPerformed
        disposeFrames();
        frmSector = new FrmSector();
        frmSector.setVisible(true);
    }//GEN-LAST:event_miRegistroSActionPerformed

    private void miActualizaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualizaSActionPerformed
        disposeFrames();
        frmUpdSector = new FrmUpdSector();
        frmUpdSector.setVisible(true);
    }//GEN-LAST:event_miActualizaSActionPerformed

    private void miCriterioAptitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriterioAptitudesActionPerformed
        disposeFrames();
        frmAptitudes = new FrmAptitudes();
        frmAptitudes.setVisible(true);
    }//GEN-LAST:event_miCriterioAptitudesActionPerformed

    private void miCriterioSectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCriterioSectoresActionPerformed
        disposeFrames();
        frmBSectores = new FrmBSectores();
        frmBSectores.setVisible(true);
    }//GEN-LAST:event_miCriterioSectoresActionPerformed

    private void miDatosDesactualizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDatosDesactualizadosActionPerformed
        disposeFrames();
        frmDesactualizados = new FrmDesactualizados();
        frmDesactualizados.setVisible(true);
    }//GEN-LAST:event_miDatosDesactualizadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mConsultas;
    private javax.swing.JMenu mSectores;
    private javax.swing.JMenu mVoluntarios;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miActualizaS;
    private javax.swing.JMenuItem miActualizacionV;
    private javax.swing.JMenuItem miCriterioAptitudes;
    private javax.swing.JMenuItem miCriterioSectores;
    private javax.swing.JMenuItem miDatosDesactualizados;
    private javax.swing.JMenuItem miRegistroS;
    private javax.swing.JMenuItem miRegistroV;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miValidacionV;
    // End of variables declaration//GEN-END:variables
}
